{% set name = "mapchete" %}
{% set version = "2025.11.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mapchete-{{ version }}.tar.gz
  sha256: e812c971016a864de0b36a2d74067420c3a4ea3bd78e128c7a2bf76f70d930ee

build:
  entry_points:
    - mapchete=mapchete.cli.mapchete:main
    - mpath=mapchete.cli.mpath:mpath
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  
requirements:
  host:
    - hatchling
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - python-dateutil
    - affine
    - aiobotocore >=1.1.2
    - aiohttp
    - boto3 >=1.14.44
    - cachetools
    - click >=7.1.1
    - click-plugins
    - click-spinner
    - dask
    - distributed
    - fiona >=1.8.13.post1
    - flask >=1.1.2,<=3.0.0
    - fsspec[http,s3] >=2023.12.0
    - geojson-pydantic
    - importlib-metadata
    - importlib-resources
    - lxml
    - matplotlib-base <3.10.0
    - memray
    - numpy >=1.16,!=2.0.1
    - oyaml
    - pydantic >=2.3.0
    - pydantic-settings >=2.0.0
    - pyproj
    - pystac[urllib3] >=1.8.2
    - pystac-client >=0.7.2
    - rasterio >=1.2.10
    - retry
    - rtree
    - s3fs >2023.9.0
    - shapely >=2.0.0
    - tilematrix >=2022.12.0
    - tqdm

test:
  imports:
    - mapchete
  commands:
    - pip check
    - mapchete --help
    - mpath --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ungarj/mapchete
  summary: Tile-based geodata processing using rasterio & Fiona
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ungarj
    - Scartography
